### ISSUE TITLE
支持React Native 0.64 版本

### ISSUE THREAD

**Issue by zhiqingchen** [wuba/taro-react-native#101]
### 问题描述
RN已发布新版本，经测试验证，目前更新到0.64后无法运行。
https://reactnative.dev/blog/2021/03/12/version-0.64

### 解决方案
> fix bug

**Comment by shinken008** [comment]
https://github.com/wuba/taro-react-native/commit/718b5d48623e47ae3ba4431c58ac283d2cdddd64

**Comment by shinken008** [comment]
taro react-native 升级到0.64.0 https://github.com/wuba/taro-react-native/commit/718b5d48623e47ae3ba4431c58ac283d2cdddd64

**Comment by shinken008** [comment]
参考 https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.0
