### ISSUE TITLE
Taro.getCurrentPages()没有page.options

### ISSUE THREAD

**Issue by iambool** [wuba/taro-react-native#105]
### 问题描述
Taro-RN，使用 Taro.getCurrentPages() 获取当前页面实例，参数跟其他端没保持一致。能拿到 page.route ，但是拿不到page.options。
node_modules/@tarojs/taro/types/api/framework/index.d.ts里面关于Taro.Page的定义虽然没options，但是实际小程序端是有的。

### 期望
期望跟小程序同步，加上page.options数据

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-react-native/pull/139

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro/pull/9319
