### ISSUE TITLE
希望能提供 react-navigation 的 navigate 方法

### ISSUE THREAD

**Issue by zhiqingchen** [wuba/taro-react-native#142]
### 问题描述

某些场景需要

### 解决方法

可以提供内部方法，方便业务使用

**Comment by tourze** [comment]
好像在页面里面用 this.navigation 能读取得到。

**Comment by zhiqingchen** [comment]
> 好像在页面里面用 this.navigation 能读取得到。

嗯嗯，页面是可以取到，页面外就比较麻烦，需要再把参数传过去

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro/commit/e160e273e0ca09e80d3cfc4b1b14e17f56c3bea4

**Comment by zhiqingchen** [comment]
```
import { __navigationRef } from '@tarojs/taro'

__navigationRef.current?.navigate
```

**Comment by zhiqingchen** [comment]
```js
import { getCurrentInstance } from '@tarojs/taro'
console.log(getCurrentInstance().rnNavigationRef?.current);
```

**Comment by zhiqingchen** [comment]
不在顶级接口暴露，转至 `Current` 对象

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro/commit/d37c2f9fd88f707e8a3bc95ad81b00248f9d2038
