### ISSUE TITLE
其他进程占用端口号时，无法启动tarorn环境

### ISSUE THREAD

**Issue by iambool** [wuba/taro-react-native#155]
### 问题描述
启动壳工程，安装APP时，会启动一个默认的RN的终端并监听8081端口号。如果不关闭这个服务，本地其他的taro rn的工程就无法顺利启动，表现如下（reset-cache拼错忽略…不影响）：
![image](https://user-images.githubusercontent.com/30134533/123607901-dc3dce80-d830-11eb-9ad2-8e0122506e6e.png)

yarn dev:rn后会直接Done掉。

### 期望
期望在dev环境启动的时候，如果默认端口或指定端口被占用了，就自动换个端口，比如本来端口是8081，自动换成8082之类的

### 复现步骤
1、Xcode打开ios壳工程，安装一个ios包（此时会启动一个监听8081的react native的服务）
2、不要关闭这个服务，直接另起一个终端，启动taro rn服务
3、此时，taro rn的服务会直接Done掉

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro/commit/ba1e620fa88ee427d1901ddd746e284b851555f1
