### ISSUE TITLE
提供跨端通用的 iconfont 解决方案

### ISSUE THREAD

**Issue by zhiqingchen** [wuba/taro-react-native#67]
### 问题描述

https://github.com/NervJS/taro/issues/8180#issuecomment-791858526

在小程序、h5中使用字体图标是比较简单的，直接下载iconfont的项目通过引用css即可，在rn端好像这样并不行，看你们提供的示例都没有带iconfont， 想问下有没有能适合rn和小程序端通用的字体图标方案呢？

### 解决方案

> todo

**Comment by tourze** [comment]
这个问题，开发者使用expo-font可以解决。

```
import React from 'react'
import PropTypes from 'prop-types';
import { Text } from '@tarojs/components';
import { useFonts } from 'expo-font';
import Theme from '@/taro-ui/Theme'
import Taro from '@tarojs/taro'
import { SIZE_MAP } from '@/taro-ui/iconfont/config'
import mergeStyle from '@/taro-util/mergeStyle'
import './index.scss';

// 组装一次
const list = require('./font_855642_ob3arf3n52r/iconfont.json').glyphs;
const fontMap = {};
list.map((item) => {
  fontMap[item.font_class] = item;
});

function IconFont ({ name, customStyle, color, onClick, className, size }) {
  const [loaded] = useFonts({
    icon: require('./font_855642_ob3arf3n52r/iconfont.ttf'),
  });

  const displayText = loaded
    ? String.fromCharCode(parseInt(fontMap[name].unicode, 16))
    : fontMap[name].name;
  console.log('displayText', displayText);

  let propStyle = {
    // 图标默认样式跟随主题色
    color: Theme.colorBrandBase(),
    fontFamily: 'icon',
  };
  if (color) {
    propStyle.color = color;
  }
  if (size) {
    propStyle.fontSize = Taro.pxTransform(SIZE_MAP[size] ? SIZE_MAP[size] : size);
  }
  const finalStyle = mergeStyle(propStyle, customStyle);

  if (!loaded) {
    return null;
  }

  return (
    <Text
      className={className}
      style={finalStyle}
      onClick={onClick} // TODO RN中 Text 不支持 onClick
    >
      {displayText}
    </Text>
  );
}

IconFont.propTypes = {
  size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  name: PropTypes.string,
  color: PropTypes.string,
  onClick: PropTypes.func,
  customStyle: PropTypes.object,
};

IconFont.defaultProps = {
  size: 'normal', // normal, small, large
  color: null,
  customStyle: {},
  onClick: () => {},
};

export default IconFont;
```

**Comment by zhiqingchen** [comment]
@tourze 你这个怎么做到各端通用？

**Comment by tourze** [comment]
> @tourze 你这个怎么做到各端通用？

其他端接入iconfont不难吧。我目前只测试了H5和RN。H5的实现是：
```
import React from 'react'
import Taro from '@tarojs/taro';
import { Text } from '@tarojs/components';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import mergeStyle from '@/taro-util/mergeStyle';
import globalColor from '../globalColor';
import { SIZE_MAP } from './config'
import './index.scss';

if (window.ICON_FONT_LOADED === undefined) {
  // h5环境下，动态插入css样式文件
  const link = document.createElement('link');
  link.type = 'text/css';
  link.rel = 'stylesheet';
  link.href = '//at.alicdn.com/t/font_855642_c5rxeiicyqi.css';
  const head = document.getElementsByTagName('head')[0];
  head.appendChild(link);
}

function IconFont ({ name, customStyle, color, onClick, className, size }) {
  let propStyle = {
    color: globalColor('color-brand-base'),
  };
  if (color) {
    propStyle.color = color;
  }

  if (size) {
    propStyle.height = propStyle.width = Taro.pxTransform(SIZE_MAP[size] ? SIZE_MAP[size] : size);
  }

  const finalStyle = mergeStyle(propStyle, customStyle);

  // h5的话，返回个text标签咯
  finalStyle.fontSize = finalStyle.height;
  delete finalStyle.height;
  delete finalStyle.width;

  return (
    <Text
      className={classNames([
        'at-font-icon',
        `at-font-icon__${name}`,
        'at-font-icon-h5',
        `at-font-icon-h5__${name}`,
        'icon',
        `icon-${name}`,
      ], className)}
      style={finalStyle}
      onClick={onClick}
    />
  );
}

IconFont.propTypes = {
  size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  name: PropTypes.string,
  color: PropTypes.string,
  onClick: PropTypes.func,
  customStyle: PropTypes.object,
};

IconFont.defaultProps = {
  size: 'normal', // normal, small, large
  color: null,
  customStyle: {},
  onClick: () => {},
};

export default IconFont;
```

**Comment by chili-kwh** [comment]
可以参考 `iconfont` 官方方案:
taro: https://github.com/iconfont-cli/taro-iconfont-cli
RN: https://github.com/iconfont-cli/react-native-iconfont-cli

**Comment by zhiqingchen** [comment]
参考以上实践案例

**Comment by tourze** [comment]
> 这个问题，开发者使用expo-font可以解决。
> 
> ```
> import React from 'react'
> import PropTypes from 'prop-types';
> import { Text } from '@tarojs/components';
> import { useFonts } from 'expo-font';
> import Theme from '@/taro-ui/Theme'
> import Taro from '@tarojs/taro'
> import { SIZE_MAP } from '@/taro-ui/iconfont/config'
> import mergeStyle from '@/taro-util/mergeStyle'
> import './index.scss';
> 
> // 组装一次
> const list = require('./font_855642_ob3arf3n52r/iconfont.json').glyphs;
> const fontMap = {};
> list.map((item) => {
>   fontMap[item.font_class] = item;
> });
> 
> function IconFont ({ name, customStyle, color, onClick, className, size }) {
>   const [loaded] = useFonts({
>     icon: require('./font_855642_ob3arf3n52r/iconfont.ttf'),
>   });
> 
>   const displayText = loaded
>     ? String.fromCharCode(parseInt(fontMap[name].unicode, 16))
>     : fontMap[name].name;
>   console.log('displayText', displayText);
> 
>   let propStyle = {
>     // 图标默认样式跟随主题色
>     color: Theme.colorBrandBase(),
>     fontFamily: 'icon',
>   };
>   if (color) {
>     propStyle.color = color;
>   }
>   if (size) {
>     propStyle.fontSize = Taro.pxTransform(SIZE_MAP[size] ? SIZE_MAP[size] : size);
>   }
>   const finalStyle = mergeStyle(propStyle, customStyle);
> 
>   if (!loaded) {
>     return null;
>   }
> 
>   return (
>     <Text
>       className={className}
>       style={finalStyle}
>       onClick={onClick} // TODO RN中 Text 不支持 onClick
>     >
>       {displayText}
>     </Text>
>   );
> }
> 
> IconFont.propTypes = {
>   size: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
>   name: PropTypes.string,
>   color: PropTypes.string,
>   onClick: PropTypes.func,
>   customStyle: PropTypes.object,
> };
> 
> IconFont.defaultProps = {
>   size: 'normal', // normal, small, large
>   color: null,
>   customStyle: {},
>   onClick: () => {},
> };
> 
> export default IconFont;
> ```

这个方案，在ios正式打包后，会有问题。
如果考虑兼容性的话，最好是小程序、H5使用ttf字体，RN使用svg（https://github.com/iconfont-cli/react-native-iconfont-cli）来渲染图标。
