### ISSUE TITLE
提供打包自动化方案

### ISSUE THREAD

**Issue by zhiqingchen** [wuba/taro-react-native#75]
### 问题描述

用户在使用 Taro 开发 APP 时，经常会配到各类环境问题，且难以解决，开发人员也难以提供帮助。

### 解决方案

> todo

**Comment by shinken008** [comment]
私有化壳子：
1. 提供 ci 先把壳子打出来，方便开发者调试。dev
2. 提供 ci 把壳子和 js 代码统一输出一个应用。publish

官方壳子工程：
每次更新壳子自动发布一个官方调试 app。

**Comment by zhiqingchen** [comment]
暂时关闭，待确认方案
