### ISSUE TITLE
Button组件，hoverStartTime属性无效

### ISSUE THREAD

**Issue by iambool** [wuba/taro-react-native#88]
### 问题描述
表单组件 - Button，hoverStartTime设置为2秒，但是实际上轻轻按下就会立即出现点击态

### 期望
hoverStartTime设置为2秒时，按下按钮2秒后才会出现点击态

### 复现代码
```jsx
<Button
    type="primary"
    hoverStartTime={2000}
    hoverStyle={{ backgroundColor: 'blue' }}
>
    点我看看
</Button>
```

**Comment by iChengbo** [comment]
@iambool 是按住不松，2秒后才会出现点击态

**Comment by iambool** [comment]
小程序的表现：
按下后立马松开，按钮2秒后会闪一下
长按2秒后，按钮会显示颜色，直到松开才会消失

**Comment by iambool** [comment]
windows上运行的工程，此属性不生效。按下也不会出现点击态

**Comment by iChengbo** [comment]
在此记录下两个属性的意思：
hoverStayTime：短按时，是指点击态持续时长，长按时则是松开后持续时长；
hoverStartTime：表示点击开始到触发 hover 态的时长

**Comment by zhiqingchen** [comment]
https://github.com/wuba/taro-react-native/pull/127
